#!/bin/bash
# Get the directory name from the user
echo "Enter the directory name: "
read SIR
# Check if the directory exists
if [ -d "$SIR" ]; 
then
  echo "The directory $SIR exists."
else
  echo "The directory $SIR does not exist."
fi
